### ISSUE TITLE
Flatpak runtime is end of life

### ISSUE THREAD

**Issue by Tracenji** [flathub/com.jaquadro.NBTExplorer#3]
for full transparency, i already posted it on the main NBTExplorer repo but not sure if i am supposed to post it there or here
[the issue on main NBTExplorer repo](https://github.com/jaquadro/NBTExplorer/issues/142)

Flatpak shows warning that used runtime is EOL, please update to a newer runtime like 23.08

`Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   com.jaquadro.NBTExplorer
`

**Comment by ignapk** [comment]
Thank you for reporting the issue :pray:

This flathub repository is indeed the correct place to create the ticket. You can think of it like this, if the program itself has a bug or a missing feature, regardless of the means of installation - be it flatpak, rpm, manual build from source code - this means it should be reported in the upstream (main) repository (in our case, it would be the jaquadro/NBTExplorer). On the other hand, if the issue only occurs when installing from a specific distributor (in our case, me :sweat_smile:), you open the ticket in the particular downstream repository, which in our case is exactly here.

The issue has been fixed now, thanks!
